<?php
/**
 * Config - the Global Configuration loaded BEFORE the Nova Application starts.
 *
 * @author Virgil-Adrian Teaca - virgil@giulianaeassociati.com
 * @version 3.0
 */

use Config\Config;

// Immutable, not mutable: values already present in the environment win. In
// production the secrets are injected by `op run` into the container
// environment and must never be silently replaced by a stale app/.env left on
// the host.
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->safeLoad();

// The application reads configuration out of $_ENV. PHP also mirrors the
// process environment into $_SERVER, and it is that copy which crash
// reporters (Sentry), profilers and phpinfo(INFO_VARIABLES) serialize. Drop
// the credentials from the mirror so they cannot ride along in a stack trace.
// $_ENV itself has to stay - Config/Database.php and friends read it below.
foreach (array(
    'DB_PASS',
    'DB_ROOT_PASSWORD',
    'MYSQL_ROOT_PASSWORD',
    'MAIL_PASS',
    'REDIS_PASS',
    'RABBITMQ_PASS',
    'RECAPTCHA_SECRET',
    'WACS_CLIENT_SECRET',
    'DCS_CLIENT_SECRET',
    'SENTRY_DSN',
    'OP_SERVICE_ACCOUNT_TOKEN',
) as $secret) {
    unset($_SERVER[$secret]);
}

/**
 * PREFER to be used in Database calls or storing Session data, default is 'nova_'
 */
define('PREFIX', $_ENV["APP_PREFIX"]);

/**
 * Setup the Config API Mode.
 * For using the 'database' mode, you need to have a database, with a table generated by 'scripts/nova_options'
 */
define('CONFIG_STORE', 'files'); // Supported: "files", "database"


/**
 * Routing configuration
 */
Config::set('routing', array(
    /*
     * The style of parameters processed on Route pattern.
     */
    'parameters' => 'named',       // Supported: "named" and "unnamed".

    /*
     * The Asset Files Serving configuration.
     */
    'assets' => array(
        // The driver type used for serving the Asset Files.
        'driver' => 'default',     // Supported: "default" and "custom".

        // The name of Assets Dispatcher used as 'custom' driver.
        'dispatcher' => 'Shared\Routing\Assets\CustomDispatcher',

        // The served file Cache Time.
        'cacheTime' => 10800,

        // The Valid Vendor Paths - be aware that improper configuration of the Valid Vendor Paths could introduce
        // severe security issues, try to limit the access to a precise area, where aren't present "unsafe" files.
        //
        // '/vendor/almasaeed2010/adminlte/dist/css/AdminLTE.min.css'
        //          ^____________________^____^____________________This are the parts of path which are validated.
        //
        'paths' => array(
            'almasaeed2010/adminlte' => array(
                'bootstrap',
                'dist',
                'plugins'
            ),
            'twbs/bootstrap' => 'dist',
        ),
    ),
));
